### ISSUE TITLE
Why does it only work on API 31 and above?

### ISSUE THREAD

**Issue by snowekim** [Albrodiaz/LocationComposeExample#2]
Is there any reason why this code doesn't work  on devices below API  31? 

Thanks!

**Comment by Albrodiaz** [comment]
I'm not sure about the issue. Android Studio won't let me start the emulator with API 30. Therefore, I don't know if I can run the project.
Only I can see is a black screen.

**Comment by snowekim** [comment]
yea it's weird because the code doesn't give any warning about requiring the use of a min API for any of the functions but the callback never triggers when running on devices below 31.
